config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  namespace :admins do
    resources :items,only: [:index, :new, :show, :edit, :create, :update, :destroy]
    resources :end_users
    resources :orders,only: [:index, :show, :update]
    resources :order_details,only: [:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :end_users,only: [:show, :edit, :update, :confirm, :destroy]

  devise_for :end_users,controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}

  namespace :end_users do
   resources :tops,only: [:index]
   resources :items,only: [:index, :show]
   resources :addresses
   resources :cart_items do
    collection do
      delete 'destroy_all'
    end
   end
   resources :orders,only: [:new, :index, :show, :create] do
      collection do
        get 'verification'
        post 'vericreate'
        get 'complete'
      end
    end
  end

  root :to => 'tops#index'

end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :end_user

	validates :postal_code, presence: true
	validates :street_address, presence: true
	validates :address, presence: true

	def full_address
		"#{self.postal_code} #{self.street_address} #{self.address}"
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :end_user
	belongs_to :item

	validates :amount, presence: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :name, presence: true
  validates :kana_surname, presence: true
  validates :kana_name, presence: true
  validates :postal_code, presence: true
  validates :street_address, presence: true
  validates :phone_number, presence: true
end

app/models/end_users.rb
module EndUsers
  def self.table_name_prefix
    'end_users_'
  end
end

app/models/item.rb
class Item < ApplicationRecord
	enum status: {販売中:0, 売り切れ:1}
	enum genre_id: {ケーキ:0, クッキー:1, プリンゼリー:2, 和菓子:3}
	validates :name, presence: true
    validates :price, presence: true
    validates :genre_id, presence: true
    validates :status, presence: true
    validates :description, presence: true

    has_many :cart_items
    has_many :order_details
    attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
	enum payment_method: {クレジットカード:0, 銀行振込:1}
	belongs_to :end_user
	has_many :order_details
	enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum make_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

    def create
		@item = Item.new(item_params)
        if @item.save
		  redirect_to admins_items_path(@item)
		else
			@item = item
			render :new
		end
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
	      redirect_to admins_item_path(@item)
	    else
	      render :edit
	    end
	end

	def destroy
		items = Item.find(params[:id])
		if items.destroy
			redirect_to admins_items_path(@item)
	    else
	    	@items = Item.all
	    	render :index
	    end
	end

	private
	def item_params
		params.require(:item).permit(:name, :price, :genre_id, :status, :description, :image)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
     def after_sign_in_path_for(resource)
         case resource
	         when Admin
	             admins_items_path
	         when EndUser
	             end_users_path
         end
     end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == Admin
            new_admin_session_path
        else
            new_end_user_session_path
        end
    end


    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :kana_surname,:surname, :kana_name, :postal_code, :street_address, :phone_number])
        devise_parameter_sanitizer.permit(:sign_in, keys:[:email])
    end

end

app/controllers/end_users/items_controller.rb
class EndUsers::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end

    private
	def item_params
	    params.require(:item).permit(:name, :price, :genre_id, :status, :description, :image)
	end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
	def show
	end

	def edit
	end

    def update
    	@end_user = EndUser.find(current_end_user.id)
	   	if @end_user.update(end_user_params)
	       redirect_to end_users_path
	     else
	      render :edit
	    end
    end


    def destroy
    	@end_user = EndUser.find(current_end_user.id)
    	 @end_user.destroy
    	  redirect_to root_path
    end

	private

	def end_user_params
     params.require(:end_user).permit( :email, :name)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
	def index
		
	end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users/addresses_helper.rb
module EndUsers::AddressesHelper
end

app/helpers/end_users/cart_items_helper.rb
module EndUsers::CartItemsHelper
end

app/helpers/end_users/items_helper.rb
module EndUsers::ItemsHelper
end

app/helpers/end_users/orders_helper.rb
module EndUsers::OrdersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
	<%= form_for(@item, url: admins_item_path) do |f| %>
	    <h4>商品画像</h4>
	    <p><%= f.attachment_field :image %></p>
      	<h4>商品名</h4>
	    <p><%= f.text_field :name %></p>
	    <h4>商品説明</h4>
	    <p><%= f.text_area :description %></p>
	    <h4>税抜価格</h4>
	  	<p><%= f.text_field :price %></p>
	  	<h4>ジャンル</h4>
	  	<p><%= f.select :genre_id, [["ケーキ", "ケーキ"], ["クッキー", "クッキー"], ["プリンゼリー", "プリンゼリー"], ["和菓子", "和菓子"]], include_blank: "選択して下さい" %></p>
	  	<h4>販売ステータス</h4>
		<label><%= f.radio_button :status, "販売中" %>販売中</label>
		<label><%= f.radio_button :status, "売り切れ" %>売り切れ</label>
	    <%= f.submit 'Update Items' %>
	<% end %>
</div>

app/views/admins/items/index.html.erb
<div class="container">
 <h1>商品一覧</h1>
    <table class="table">
		<thead class="thead bg-info text-white">
			<tr>
				<th scope="col">商品ID</th>
				<th scope="col">商品名</th>
				<th scope="col">税抜価格</th>
				<th scope="col">ジャンル</th>
				<th scope="col">販売ステータス</th>
				<th scope="col"></th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			<% @items.each do |item| %>
				<tr>
					<td><%= item.id %></td>
					<td><%= item.name %></td>
					<td>¥<%= item.price %></td>
					<td><%= item.genre_id %></td>
					<td><%= item.status %></td>
					<td><button type="button" class="btn btn-warning"><%= link_to "詳細", admins_item_path(item.id) %></td></button>
					<td><button type="button" class="btn btn-danger"><%= link_to "Destroy", admins_item_path(item.id), method: :delete %></button></td>
				</tr>
		    <% end %>
		</tbody>
	</table>
</div>

app/views/admins/items/new.html.erb
<div class="container">
	<h1>商品 新規登録画面</h1>
	<%= form_for(@item, url: admins_items_path) do |f| %>
	    <h4>商品画像</h4>
	    <p><%= f.attachment_field :image %></p>
      	<h4>商品名</h4>
	    <p><%= f.text_field :name %></p>
	    <h4>商品説明</h4>
	    <p><%= f.text_area :description %></p>
	    <h4>税抜価格</h4>
	  	<p><%= f.text_field :price %></p>
	  	<h4>ジャンル</h4>
	  	<p><%= f.select :genre_id, [["ケーキ", "ケーキ"], ["クッキー", "クッキー"], ["プリンゼリー", "プリンゼリー"], ["和菓子", "和菓子"]], include_blank: "選択して下さい" %></p>
	  	<h4>販売ステータス</h4>
		<label><%= f.radio_button :status, "販売中" %>販売中</label>
		<label><%= f.radio_button :status, "売り切れ" %>売り切れ</label>
	    <%= f.submit 'Create Items' %>
	 <% end %>
</div>

app/views/admins/items/show.html.erb
<div class="container">
	<h2>商品詳細</h2>
	<table class="table">
		<thead class="thead bg-info text-white">
			<tr>
				<th scope="col"></th>
				<th scope="col">商品名</th>
				<th scope="col">商品説明</th>
				<th scope="col">税抜価格</th>
				<th scope="col">ジャンル</th>
				<th scope="col">販売ステータス</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td><%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %></td>
					<td><%= @item.name %></td>
					<td><%= @item.description %></td>
					<td>¥<%= @item.price %></td>
		            <td><%= @item.genre_id %></td>
		            <td><%= @item.status %></td>
		            <td><%= link_to "編集", edit_admins_item_path(@item) %></td>
				</tr>
		</tbody>
	</table>
</div>