config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  namespace :admins do
    resources :items,only: [:index, :new, :show, :edit, :create, :update, :destroy]
    resources :end_users
    resources :orders,only: [:index, :show, :update]
    resources :order_details,only: [:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :end_users,only: [:show, :edit, :update, :confirm, :destroy]

  devise_for :end_users,controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}

  namespace :end_users do
   resources :tops,only: [:index]
   resources :items,only: [:index, :show]
   resources :addresses
   resources :cart_items do
    collection do
      delete 'destroy_all'
    end
   end
   resources :orders,only: [:new, :index, :show, :create] do
      collection do
        get 'verification'
        post 'vericreate'
        get 'complete'
      end
    end
  end

  root :to => 'tops#index'

end

app/models/order.rb
class Order < ApplicationRecord
	enum payment_method: {クレジットカード:0, 銀行振込:1}
	belongs_to :end_user
	has_many :order_details
	enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
        @order_details = @order.order_details
        @total_price = 0
    end

    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
      
        if @order.order_status_before_type_cast == 1
            @order.order_details.each do |order_detail|
                order_detail.update(make_status: 1) 
            end
        end
        redirect_to admins_order_path(@order.id)
    end

    private
    def order_params
        params.require(:order).permit(:order_status)
    end
end

app/controllers/end_users/orders_controller.rb
class EndUsers::OrdersController < ApplicationController
	def index

	end

	def show
		
	end

	def new
		@order = Order.new
		@end_user = EndUser.find(current_end_user.id)
		@addresses = current_end_user.addresses.all
	end


	def verification
		if session[:order]["payment_method"] == nil || session[:address_btn] == nil
            redirect_to new_end_users_order_path
		end
		
		@order = session[:order]
		@end_user = current_end_user
		@postage = 1000
	    @total_price = 0
	    @prices = 0
	    current_end_user.cart_items.each do |cart_item|
	      price = 0
	      price = cart_item.item.price * cart_item.amount
	      @prices = @prices + cart_item.item.price
	      @total_price = @total_price + price
	    end
	    @prices = (@prices * 1.10).round
	    @total_price = @total_price * 1.10
		@total_price = (@total_price + @postage).round
		@order = Order.new
	end

	def create
		order = Order.new(end_user_id: current_end_user.id,
						  postage: 1000,
						  payment_method: session[:order]["payment_method"],
						  address: session[:order]["address"],
						  postal_code: session[:order]["postal_code"],
						  total_price: params[:order][:total_price],
						  street_address: session[:order]["street_address"]
		                  )
		order.save
		session[:order].clear

		current_end_user.cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.item_id = cart_item.item.id
			order_detail.order_id = order.id
			order_detail.amount = cart_item.amount
			order_detail.purchase_price = cart_item.item.price
			order_detail.save
		end

		current_end_user.cart_items.destroy_all


		redirect_to complete_end_users_orders_path
	end


	def vericreate

		session[:order] = Order.new(order_params)
		session[:order][:end_user_id] = current_end_user.id
		if params["address_btn"].to_i == 1
		   session[:order]["postal_code"] = current_end_user.postal_code
		   session[:order]["street_address"] = current_end_user.street_address
		   session[:order]["address"] = current_end_user.name
	  
		elsif params["address_btn"].to_i == 2
			address = Address.find(params[:order][:address_info])
			session[:order]["postal_code"] = address.postal_code
			session[:order]["street_address"] = address.street_address
			session[:order]["address"] = address.address
		else   
			address = Address.new(address_params)
			address.end_user_id = current_end_user.id
			address.save

			session[:order]["postal_code"] = address.postal_code
			session[:order]["street_address"] = address.street_address
			session[:order]["address"] = address.address
		end
		
		session[:address_btn] = params[:address_btn]
		session[:order][:end_user_id] = current_end_user.id
		session[:order]["postage"] = 1000
		session[:order]["payment_method"] = order_params[:payment_method]

		redirect_to verification_end_users_orders_path
	end

	def complete
		@order = Order.all
	end

    private
	def address_params
		params.require(:address).permit(:end_user_id, :street_address, :postal_code, :address)
	end

	def verification_params
		params.require(:order).permit(:end_user_id, :order_status, :total_price, :payment, :postal_code, :postage, :address, :street_address)
	end

	def order_params
		params.require(:order).permit(:end_user_id, :address_btn, :payment, :street_address, :postal_code, :address, :payment_method)
	end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/end_users/orders_helper.rb
module EndUsers::OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="container">
 <div class="row">
  <h1>注文一覧画面</h1>
 </div>
 <div class="row">
    <table class="table">
        <thead class="thead bg-info text-white">
            <tr>
                <th>購入日時</th>
                <th>購入者</th>
                <th>注文個数</th>
                <th>注文ステータス</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @orders.each do |order| %>
                <tr>
                    <td><%= l order.created_at %></td>
                    <td><%= order.end_user.surname %><%= order.end_user.name %></td>
                    <td>
                        <% total_amount = 0 %>
                        <% order.order_details.each do |order_detail| %>
                            <% total_amount += order_detail.amount %>
                        <% end %>
                        <%= total_amount %>
                    </td>
                    <td><%= order.order_status %></td>
                    <td><%= link_to "show", admins_order_path(order) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
 </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
    <div class="row">
     <h1>注文詳細画面</h1>
    </div>
    <div class="row">
      <p>購入者</p>
      <label><%= @order.end_user.surname %><%= @order.end_user.name %></label>
    </div>
    <div class="row">
      <p>配送先</p>
      <label>〒<%= @order.postal_code %></label>
      <label><%= @order.street_address %></label>
      <label><%= @order.address %></label>
    </div>
    <div class="row">
      <p>支払方法</p>
      <label><%= @order.payment_method %></label>
    </div>
    <div class="row">
      <p>注文ステータス</p>
      <label>
        <%= form_for(@order, url: admins_order_path) do |f| %>
            <%= f.select :order_status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"]], include_blank: "選択して下さい" %>
            <%= f.submit '更新' %>
        <% end %>
      </label>
    </div>

    <div class="row">
        <table class="table">
            <thead class="thead bg-info text-white">
                <tr>
                    <th>商品名</th>
                    <th>単価(税込)</th>
                    <th>数量</th>
                    <th>小計</th>
                    <th>製作ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @order_details.each do |order_detail| %>
                    <tr>
                        <td><%= order_detail.item.name %></td>
                        <td><%= (order_detail.item.price*1.1).round %></td>
                        <td><%= order_detail.amount %></td>
                        <td>
                        　　　<%= ((order_detail.item.price*1.1).round)*(order_detail.amount) %>
                        　　　<% @total_price += (order_detail.item.price*1.1)*(order_detail.amount) %>
                        </td>
                        <td>
                            <%= form_with(model: order_detail, url: admins_order_detail_path(order_detail), method: :patch, local: true) do |f| %>
                                <%= f.select :make_status, [["着手不可", "着手不可"], ["製作待ち", "製作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"]], include_blank: "選択して下さい" %>
                                <%= f.submit '更新' %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
       </table>
    </div>

    <div class="row">
        <p>商品合計</p>
        <label><%= (@total_price).round %>円</label>
    </div>
    <div class="row">
        <p>送料</p>
        <label><%= @order.postage %>円</label>
    </div>
    <div class="row">
        <p>請求金額合計</p>
        <label><%= (@total_price+@order.postage).round %>円</label>
    </div>
</div>